# @package _global_

half: True
grad_scaler: True
device: 'cuda:0'
seed: 2525
progress_bar: True

save_model: True
save_interval: 50

epochs: 1000
val_every: 10
es_patience: 100000
es_min_delta: 0.0001
es_metric: 'Train/imagegeneration'
scheduler_metric: 'Train/imagegeneration'
optimized_metric: "Val/imagegeneration"