# @package dataset

name: "SpaceNet7Dataset"

load_params:
  root: "${storage_dir}/spacenet7/SN7_buildings_train/train"
save_in_memory: false

shuffle: True
batch_size: 64
num_workers: 8
pin_memory: true
drop_last: true

subset: 0.0
update_every: 1

transform: train/spacenet7

# mixup_args:
#  mixup_alpha: 0.0
#  cutmix_alpha: 1.0
#  cutmix_minmax:
#  prob: 1.0
#  switch_prob: 0.0
#  mode: 'batch'
#  label_smoothing: 0.1
#  num_classes: 5



